rhsso:
  # Generate this through the command line using
  # echo "$(oc get route keycloak --namespace backstage -o json | jq -r '.spec.host')/auth"
  baseUrl: https://keycloak-backstage.apps.cluster-77bph.77bph.sandbox1927.opentlc.com/auth
  # The pre-set clientId set by the RHSSO Chart
  clientId: backstage
  # Found in Keycloak admin console, see above
  clientSecret: 1Ti3YH3pqadiVxpXD0cru2UZb4wJQisn
  # Enable the backstage plugin
  backstagePluginEnabled: true
oauth:
  enabled: true

## There is a secret created via the template/
backstage:
  companyName: "JLand LLC"
  port: 7007
  # The base URL for the frontend application e.g. https://<hostname>
  baseUrl: "https://assemble-demo.apps.cluster-77bph.77bph.sandbox1927.opentlc.com"

  # Ignore NodeJS insecure certificate warnings
  tlsInsecure: false

  database:
    client: pg
    connection:
      host: "${POSTGRES_HOST}"
      port: "${POSTGRES_PORT}"
      user: "${POSTGRES_USER}"
      password: "${POSTGRES_ADMIN_PASSWORD}"

  ## Override Catalog with here
  catalog:
      #  Add Template to the allowed types
      rules:
        - allow: [Component, System, API, Resource, Location, Template]
      locations:
        # Add reference to sample template
        - type: url
          target: https://github.com/janus-idp/software-templates/blob/main/scaffolder-templates/quarkus-web-template/template.yaml
  

github:
  enabled: true
  token: "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"