{{- if not .Values.postgres.external }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "janus-backstage.postgresql.name" . }}
  labels:
    {{- include "janus-backstage.postgresql.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.postgres.database_port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "janus-backstage.postgresql.selectorLabels" . | nindent 4 }}
{{- end }}
