{{- if .Values.vault.enabled }}
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: {{ .Release.Name }}-postgresql-secret
spec:
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: {{ .Release.Name }}-reader
        serviceAccount:
          name: default
      name: postgresqlsecret
      path: kv/{{ .Release.Name }}/postgresql
  output:
    name: {{ include "janus-backstage.postgresql.name" . }}
    stringData:
      databasePassword: '{{ "{{" }} .postgresqlsecret.adminpassword {{ "}}" }}'
      databaseName: "{{ .Values.postgres.database_name }}"
      databaseUser: "{{ .Values.postgres.database_user }}"
      databasePort: "{{ .Values.postgres.database_port }}"
      databaseHost: "{{ include "janus-backstage.postgresql.name" . }}"
    type: Opaque
{{- end }}
