{{- if .Values.repositoryCredentials }}
{{- range $cred := .Values.repositoryCredentials }}
{{- range $ns := $.Values.namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $cred.name }}
  namespace: {{ $ns }}
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  username:  {{ $cred.username | quote }}
  password: {{ $cred.password | quote }}
  type: {{ $cred.type }}
  url: {{ $cred.url }}
{{- end }}
{{- end }}
{{- end }}