{{- if .Values.vault.enabled }}
kind: SecretEngineMount
apiVersion: redhatcop.redhat.io/v1alpha1
metadata:
  name: {{ .Release.Name }}
  namespace: "{{ .Values.vaultconfig.namespace }}"
spec:
  authentication:
    path: kubernetes
    role: policy-admin
  path: kv
  type: kv
{{- end }}
