apiVersion: redhatcop.redhat.io/v1alpha1
kind: KubernetesAuthEngineRole
metadata:
  name: devspaces-vault-role
  namespace: vault-admin
spec:
  # Add fields here
  authentication: 
    path: kubernetes
    role: policy-admin
  path: kubernetes
  policies:
    - devspaces-read-token  
  targetServiceAccounts:
  - default      
  targetNamespaces:
    targetNamespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values: ["openshift-operators"]