{{- if .Values.vault.enabled }}
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: PasswordPolicy
metadata:
  name: postgresql-random-policy
  namespace: "{{ .Values.vaultconfig.namespace }}"
spec:
  # Add fields here
  authentication:
    path: kubernetes
    role: policy-admin
  passwordPolicy: |
    length = 20
    rule "charset" {
      charset = "abcdefghijklmnopqrstuvwxyz"
    }
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: postgresql
  namespace: "{{ .Values.vaultconfig.namespace }}"
spec:
  authentication: 
    path: kubernetes
    role: policy-admin
  path: kv/{{ .Release.Name }}
  secretKey: adminpassword
  secretFormat:
    passwordPolicyName: postgresql-random-policy
{{- end }}
