---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rhsso-cluster-auth.clientSecretName" . }}
  namespace: openshift-config
  labels:
    {{- include "rhsso-cluster-auth.labels" . | nindent 4 }}
data:
