apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: {{ .Values.keycloak.client.name }}
  labels:
    {{- include "rhsso-cluster-auth.labels" . | nindent 4 }}
spec:
  realmSelector:
    matchLabels:
      {{- include "rhsso-cluster-auth.selectorLabels" . | nindent 6 }}
  client:
    clientId: {{ .Values.keycloak.client.name }}
    clientAuthenticatorType: client-secret
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    implicitFlowEnabled: false
    consentRequired: false
    redirectUris:
      - "{{ include "rhsso-cluster-auth.redirecturi" .}}"
