apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: {{ template "rhsso-cluster-auth.name" . }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    {{- include "rhsso-cluster-auth.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.keycloak.instances }}
  externalAccess:
    enabled: true
