---
- name: Gather Cluster Info.
  gather_facts: false
  hosts: 'localhost'
  tasks:
  - name: Determine Host
    shell: "oc cluster-info | grep -Eo '.cluster(.*?).com'"
    register: cluster_response
  - name: Extract Cluster
    set_fact:
      cluster_host: "{{ cluster_response.stdout }}"
- name: Install Cert Manager Operator Chart.
  hosts: 'localhost'
  tasks:
  - name: Run Cert Manager Helm Chart
    with_items: "{{ env }}"
    kubernetes.core.helm:
      state: present
      name: cert-manager
      namespace: "openshift-operators"
      chart_ref: ../../charts/operator
      values_files: ["../../charts/operator/values-certmanager-operator.yaml"]
- name: Install Vault Config Operator Chart.
  hosts: 'localhost'
  tasks:
  - name: Run Vault Config Helm Chart
    with_items: "{{ env }}"
    kubernetes.core.helm:
      state: present
      name: vault-config-operator
      namespace: "{{ item.vaultconfignamespace }}"
      chart_ref: ../../charts/operator
      values_files: ["../../charts/operator/values-vault-config-operator.yaml"]
      create_namespace: true
- name: Install Vault Operator Chart.
  hosts: 'localhost'
  tasks:
  - name: Wait for Cert Manager to be Ready
    with_items: "{{ env }}"
    kubernetes.core.k8s_info:
      api_version:  cert-manager.io/v1
      kind: ClusterIssuer
    register: cm_crd
    until: cm_crd.api_found == true
    retries: 40
    delay: 5
  - name: Pause until Cert Manager is Ready
    pause:
      seconds: 10
  - name: Helm Dependency Update
    shell: "helm dep update"
    args:
      chdir: ../../charts/vault
    register: sso_admin_pwd_rsp
  - name: Run Vault Helm Chart
    with_items: "{{ env }}"
    kubernetes.core.helm:
      state: present
      name: vault
      namespace: "{{ item.vaultnamespace }}"
      chart_ref: ../../charts/vault
      values:
        dns:
          zone: "{{ cluster_host[1:] }}"
      create_namespace: true
- name: Install Vault Config Chart.
  hosts: 'localhost'
  tasks:
  # TODO revisit this to see if there is a better way to create this secret
  - name: Create sshKey Secret
    with_items: "{{ env }}"
    shell: "printf \"apiVersion: v1\nkind: Secret\nmetadata:\n  name: vault-github-plugin-creds\ntype: kubernetes.io/ssh-auth\nstringData:\n  github_app_id: $(echo \"\\\"\"$GITHUB_APP_ID\"\\\"\")\n  github_org: $(echo \"\\\"\"$GITHUB_ORGANIZATION\"\\\"\")\n  ssh-privatekey: |\n$(cat $GITHUB_KEY_FILE | sed 's/^/    /')\" | oc apply -f - -n vault-admin"
  - name: Run Vault Config Chart
    with_items: "{{ env }}"
    kubernetes.core.helm:
      state: present
      name: vault-config
      namespace: "vault-admin"
      chart_ref: ../../charts/vault-config
      values:
        git:
          organization: "{{ lookup('ansible.builtin.env', 'GITHUB_ORGANIZATION') }}"
          applicationId: "{{ lookup('ansible.builtin.env', 'GITHUB_APP_ID') }}"
- name: Install RHSSO Operator Chart.
  hosts: 'localhost'
  tasks:
  - name: Run RHSSO Helm Chart
    with_items: "{{ env }}"
    kubernetes.core.helm:
      state: present
      name: rhsso-operator
      namespace: "{{ item.namespace }}"
      chart_ref: ../../charts/operator
      values_files: ["../../charts/operator/values-rhsso-operator.yaml"]
      create_namespace: true
- name: Install Git Webhook Operator
  hosts: 'localhost'
  tasks:
  - name: Run Git Webhook Operator Helm Chart
    with_items: "{{ env }}"
    kubernetes.core.helm:
      state: present
      name: gitwebhook-operator
      namespace: "{{ item.gitwebhooknamespace }}"
      chart_ref: ../../charts/operator
      values_files: ["../../charts/operator/values-gitwebhook-operator.yaml"]
      create_namespace: true
- name: Install OpenShift Pipelines Operator Chart.
  hosts: 'localhost'
  tasks:
  - name: Run Pipelines Operator Helm Chart
    with_items: "{{ env }}"
    kubernetes.core.helm:
      state: present
      name: pipelines
      namespace: "{{ item.pipelinesnamespace }}"
      chart_ref: ../../charts/pipelines-operator
      create_namespace: true
- name: Install RHSSO Backstage Chart.
  hosts: 'localhost'
  tasks:
  - name: Wait for KeyCloak CRD
    with_items: "{{ env }}"
    kubernetes.core.k8s_info:
      api_version: keycloak.org/v1alpha1
      kind: Keycloak
    register: kc_crd
    until: kc_crd.api_found == true
    retries: 40
    delay: 5
  - name: Pause until Keycloak is Ready
    pause:
      seconds: 10
  - name: Run RHSSO Backstage Helm Chart
    with_items: "{{ env }}"
    kubernetes.core.helm:
      state: present
      name: rhsso-backstage
      namespace: "{{ item.namespace }}"
      chart_ref: ../../charts/rhsso-backstage
      values:
        keycloak:
          realm:
            identityProvider:
              clientId: "{{ lookup('ansible.builtin.env', 'GITHUB_KEYCLOAK_CLIENT_ID') }}"
              clientSecret: "{{ lookup('ansible.builtin.env', 'GITHUB_KEYCLOAK_CLIENT_SECRET') }}"
              enabled: "{{ false if lookup('ansible.builtin.env', 'GITHUB_KEYCLOAK_CLIENT_SECRET') == '' else true }}"
        backstage:
          host: "assemble-demo.apps{{ cluster_host }}"
      create_namespace: true
  - name: Wait for Keycloak to be Ready
    with_items: "{{ env }}"
    uri:
      url: https://keycloak-{{ item.namespace }}.apps{{ cluster_host }}/auth
      status_code: 200
    register: result
    until: result.status == 200
    retries: 300
    delay: 2
  - name: Pause until Keycloak is initialized
    pause:
      seconds: 10
  - name: Fetching RHSSO Admin Credentials
    with_items: "{{ env }}"
    shell: "oc -n {{ item.namespace }} get secret credential-rhsso-backstage --template='{{ '{{' }}.data.ADMIN_PASSWORD{{ '}}' }}' | base64 -d"
    register: sso_admin_pwd_rsp
  - name: Extract Password
    set_fact:
      sso_admin_pwd: "{{ sso_admin_pwd_rsp.results[0].stdout }}"
      keycloak_namespce: "{{ sso_admin_pwd_rsp.results[0].item.namespace }}"
  - name: Get RHSSO Auth Token
    uri:
      url: https://keycloak-{{ keycloak_namespce }}.apps{{ cluster_host }}/auth/realms/master/protocol/openid-connect/token
      method: POST
      body_format: form-urlencoded
      body:
        grant_type: "password"
        client_id: "admin-cli"
        username: "admin"
        password: "{{ sso_admin_pwd }}"
      return_content: true
    register: token_rsp
  - name: Extract Token
    set_fact:
      access_token: "{{ token_rsp.json.access_token }}"
  - name: Get Backstage Client UUID
    uri:
      url: https://keycloak-{{ keycloak_namespce }}.apps{{ cluster_host }}/auth/admin/realms/backstage/clients?clientId=backstage
      status_code: 200
      method: GET
      headers:
        Authorization: "bearer {{ access_token }}"
      return_content: true
    register: client_uuid_rsp
  - name: Extract UUID
    set_fact:
      client_uuid: "{{ client_uuid_rsp.json[0].id }}"
  - name: Get Backstage Client Secret
    uri:
      url: https://keycloak-{{ keycloak_namespce }}.apps{{ cluster_host }}/auth/admin/realms/backstage/clients/{{ client_uuid }}/client-secret
      method: GET
      headers:
        Authorization: "bearer {{ access_token }}"
      return_content: true
    register: client_secret_rsp
  - name: Extract Client Secret
    set_fact:
      client_secret: "{{ client_secret_rsp.json.value }}"
- name: Install and Configure GitOps.
  hosts: 'localhost'
  tasks:
  - name: Install GitOps Helm Chart
    with_items: "{{ env }}"
    kubernetes.core.helm:
      state: present
      name: argocd
      namespace: "{{ item.gitopsnamespace }}"
      chart_ref: ../../charts/gitops-operator
      values:
        namespaces:
          - assemble-argocd
          - infra-argocd
      create_namespace: true
  - name: Apply ApplicationSet for Infra Deployment
    with_items: "{{ env }}"
    kubernetes.core.helm:
      state: present
      name: infra-argocd
      namespace: "{{ item.gitopsinfranamespace }}"
      chart_ref: ../../charts/applicationset
- name: Install Backstage Chart.
  hosts: 'localhost'
  tasks:
  - name: Fetching ArgoCD Admin Credentials
    with_items: "{{ env }}"
    shell: "oc -n {{ item.gitopsnamespace }} get secret argocd-cluster --template='{{ '{{' }}index .data \"admin.password\"{{ '}}' }}' | base64 -d"
    register: argocd_admin_pwd_rsp
  - name: Extract Password
    set_fact:
      argocd_admin_pwd: "{{ argocd_admin_pwd_rsp.results[0].stdout }}"
  - name: Fetching Default Service Account Token
    with_items: "{{ env }}"
    shell: "oc create token default -n default"
    register: svc_account_token_rsp
  - name: Extract Token
    set_fact:
      svc_account_token: "{{ svc_account_token_rsp.results[0].stdout }}"
  - name: Fetching GitHub App Private Key
    with_items: "{{ env }}"
    shell: "cat $GITHUB_KEY_FILE"
    register: github_private_key_rsp
  - name: Extract Private Key
    set_fact:
      github_private_key: "{{ github_private_key_rsp.results[0].stdout }}"
  - name: Run Backstage Helm Chart
    with_items: "{{ env }}"
    kubernetes.core.helm:
      state: present
      name: assemble-dev
      namespace: "{{ item.namespace }}"
      chart_ref: ../../charts/assemble-backstage
      values:
        rhsso:
          baseUrl: "https://keycloak-{{ item.namespace }}.apps{{ cluster_host }}/auth"
          clientId: "backstage"
          clientSecret: "{{ client_secret }}"
          backstagePluginEnabled: true
        backstage:
          baseUrl: "https://assemble-demo.apps{{ cluster_host }}"
          catalog:
            locations:
              - type: url
                target: https://github.com/{{ lookup('ansible.builtin.env', 'GITHUB_ORGANIZATION') }}/software-templates/blob/main/scaffolder-templates/quarkus-web-template/template.yaml
                rules:
                  - allow: [Template]
        oauth:
          enabled: true
        postgres:
          database_password: "postgres"
        github:
          enabled: "{{ false if lookup('ansible.builtin.env', 'GITHUB_APP_ID') == '' else true }}"
          appId: "{{ lookup('ansible.builtin.env', 'GITHUB_APP_ID') }}"
          clientId: "{{ lookup('ansible.builtin.env', 'GITHUB_APP_CLIENT_ID') }}"
          clientSecret: "{{ lookup('ansible.builtin.env', 'GITHUB_APP_CLIENT_SECRET') }}"
          privateKey: "{{ github_private_key }}"
        argocd:
          enabled: true
          username: "admin"
          password: "{{ argocd_admin_pwd }}"
          waitCycles: 25
          url: "https://argocd-server-{{ item.gitopsnamespace }}.apps{{ cluster_host }}"
        auth:
          github:
            enabled: true
            clientId: "{{ lookup('ansible.builtin.env', 'GITHUB_BACKSTAGE_CLIENT_ID') }}"
            clientSecret: "{{ lookup('ansible.builtin.env', 'GITHUB_BACKSTAGE_CLIENT_SECRET') }}"
        kubernetes:
          enabled: true
          url: "https://api{{ cluster_host }}"
          token: "{{ svc_account_token }}"
      create_namespace: true
- name: Populate Vault with Secrets.
  hosts: 'localhost'
  tasks:
  - name: Fetching Vault Token
    with_items: "{{ env }}"
    shell: "oc -n {{ item.vaultnamespace }} get secret vault-init --template='{{ '{{' }}index .data \"root_token\"{{ '}}' }}' | base64 -d"
    register: vault_token_rsp
  - name: Extract Vault Token
    set_fact:
      vault_token: "{{ vault_token_rsp.results[0].stdout }}"
  - name: Populate Vault with Dev Spaces Secrets
    community.hashi_vault.vault_write:
      url: "https://vault-vault.apps{{ cluster_host }}"
      path: kv/assemble-dev/dev-spaces
      validate_certs: false
      data:
        id: "{{ lookup('ansible.builtin.env', 'GITHUB_DEV_SPACES_CLIENT_ID') }}"
        secret: "{{ lookup('ansible.builtin.env', 'GITHUB_DEV_SPACES_CLIENT_SECRET') }}"
      token: "{{ vault_token }}"