---
- name: Gather Cluster Info.
  gather_facts: false
  hosts: 'localhost'
  tasks:
  - name: Determine Host
    shell: "oc cluster-info | grep -Eo '.cluster(.*?).com'"
    register: cluster_response
  - name: Set Dev Spaces Instance
    set_fact:
      cluster_base_url: "{{ cluster_response.stdout }}"
  - debug: var=cluster_response.stdout_lines
- name: Customize Software Template
  gather_facts: false
  hosts: 'localhost'
  tasks:
  - name: Reset Local
    ansible.builtin.file:
      path: ../../../software-templates
      state: absent
  - name: Insert Dev Spaces Instance Information
    shell: |
      cd ../../../
      git clone git@github.com:{{ lookup('ansible.builtin.env', 'GITHUB_ORGANIZATION') }}/software-templates.git
      cd software-templates
      find . -type f -path './scaffolder-templates/quarkus-web-template/template.yaml' -exec sed -i '' -E "s/\.cluster-[a-z0-9]{5}\.[a-z0-9]{5}\.sandbox[0-9]{1,5}\.opentlc\.com/{{ cluster_base_url }}/g" {} +
      git add -A
      git commit -m "initial customization"
      git push
    environment:
        LC_CTYPE: C
        LANG: C
    register: result
  - debug: var=result.stdout_lines