apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
spec:
  dnsNames:
    - '{{ print  .Release.Name "-"  .Release.Namespace ".apps." .Values.dns.zone }}'
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.certificate.clusterIssuer }}
  secretName: vault-cert
