---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-scc-role 
  namespace: openshift-operators
rules:
- apiGroups:
  - security.openshift.io 
  resourceNames:
  - cert-manager-restricted
  resources:
  - securitycontextconstraints 
  verbs: 
  - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager-restricted-scc
  namespace: openshift-operators
subjects:
  - kind: ServiceAccount
    name: cert-manager
  - kind: ServiceAccount
    name: cert-manager-cainjector
  - kind: ServiceAccount
    name: cert-manager-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-scc-role
