site_name: Janus IDP Demo
site_url: https://janus-idp.github.io/assemble-platforms/
site_description: From Idea to Production Faster
repo_name: janus-idp/assemble-platforms
repo_url: https://github.com/janus-idp/assemble-platforms.git
theme:
  name: material
  # logo: img/icon-white.png
  # favicon: img/favicon.png
  font:
    text: Red Hat Text
    code: Red Hat Monospace
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: assemble
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - content.code.copy
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
nav:
  - Home: index.md
  - Install:
    - Getting Started: getting_started/getting-started.md
  - Architecture: architecture.md
  - Demo: demo.md
