apiVersion: v1
kind: Secret
metadata:
  name: assemble-config
stringData:
  app-config.yaml: |- 
    {{- tpl (.Files.Get "config/app-config.yaml") . | nindent 4 }}

{{- if .Values.additionalConfig }}
  additional-config.yaml: |
    {{- toYaml .Values.additionalConfig | nindent 4 }}
{{- end }}
