{{- if .Values.oauth.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "assemble-backstage.oauthProxy.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "assemble-backstage.labels" . | nindent 4 }}
stringData:
  clientId: {{ required "clientId must be provided" .Values.oauth.clientId }}
  clientSecret: {{ required "clientSecret must be provided" .Values.oauth.clientSecret }}
  cookieSecret: {{ .Values.oauth.cookieSecret }}
type: Opaque
{{- end }}