{{- if not .Values.postgres.external }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "assemble-backstage.fullname" . }}-postgresql
  labels:
    app.kubernetes.io/name: {{ include "assemble-backstage.fullname" . }}-postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.postgres.database_port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/instance: backstage
    app.kubernetes.io/name: {{ include "assemble-backstage.fullname" . }}-postgresql
{{- end }}
