{{- if .Values.postgres.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  {{ include "assemble-backstage.fullname" . }}-postgresql
{{- if .Values.postgres.storage.labels  }}
  labels:
    {{- toYaml .Values.postgres.storage.labels | nindent 4 }}
{{- end }}
  annotations:
    kubernetes.io/reclaimPolicy: Delete 
spec:
{{- if .Values.postgres.storage.storageClass }}
  storageClassName: "{{ .Values.postgres.storage.storageClass }}"
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
{{- end }}
