{{- if .Values.postgres }}
{{- if not .Values.vault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "assemble-backstage.postgresql.labels" . | nindent 4 }}
  name: {{ include "assemble-backstage.postgresql.name" . }}
stringData:
  databaseName: "{{ .Values.postgres.database_name }}"
  databaseUser: "{{ .Values.postgres.database_user }}"
  databasePort: "{{ .Values.postgres.database_port }}"
{{- if .Values.postgres.database_host }}
  databaseHost: "{{ .Values.postgres.database_host }}"
{{- else }}
  databaseHost: "{{ include "assemble-backstage.postgresql.name" . }}"
{{- end }}
  {{- ( include "gen.postgres-password" . ) | indent 2 -}}
{{- end }}
{{- end }}
