apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "assemble-backstage.fullname" . }}
  labels:
    {{- include "assemble-backstage.labels" . | nindent 4 }}
spec:
  host: {{ (trimPrefix  "https://" .Values.backstage.baseUrl) | trimPrefix  "http://" | trimSuffix "/"  }}
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ include "assemble-backstage.fullname" . }}
    weight: 100
  wildcardPolicy: None
