apiVersion: v1
kind: Service
metadata:
  name: {{ include "assemble-backstage.fullname" . }}
  labels:
    {{- include "assemble-backstage.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.oauth.enabled | ternary .Values.oauth.port .Values.backstage.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "assemble-backstage.selectorLabels" . | nindent 4 }}
